apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: desafio-kubernetes
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: troque-esta-senha
  PGRST_DB_URI: postgres://postgres:troque-esta-senha@postgres-service:5432/desafio